sudo: required

services: docker
before_install:
  - docker build . -t ml_env_python:latest
script:
  - echo "No test here!"

deploy:
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login -username "$DOCKER_USERNAME" --password-stdin
    docker tag ml_env_python:latest tokupooh0910/ml_env:${TRAVIS_BUILD_NUMBER}
    docker push tokupooh0910/ml_env:${TRAVIS_BUILD_NUMBER}
    docker tag tokupooh0910/ml_env:${TRAVIS_BUILD_NUMBER} tokupooh0910/ml_env:latest
    docker push tokupooh0910/ml_env:latest
  on:
    branch: main
